name: generate-contribution-snake-animation

on:
  schedule:
    - cron: "0 18 * * *" # Midnight (12:00 AM) Dhaka (UTC +6) Timezone
  workflow_dispatch:

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: checkout-current-branch # latest
        uses: actions/checkout@v6

      - name: generate-snake-svgs # animated and themed
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: commit-snake-svgs # generated svg files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "ci: update snake animation svgs"
          file_pattern: "github-snake.svg github-snake-dark.svg"
